### ISSUE TITLE
cargo run crashes

### ISSUE THREAD

**Issue by bikallem** [aochagavia/rocket#1]
I am getting the error below while trying to run, i.e. `cargo run --release`

> Running `target/release/rocket`
> [glutin] x error code=42 major=0 minor=0!
> thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("GL context creation failed")', /home/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:729
> An unknown error occurred

Is there any lib that I am missing? I am using stable rust.

**Comment by aochagavia** [comment]
I am unable to reproduce this error in my machine. Do you have OpenGL installed?

**Comment by pmarcelll** [comment]
Your system doesn't support OpenGL 3.2 and GlutinWindow::new() contains an unwrap(). Unfortunately I couldn't find a good way to find out the supported OpenGL version at runtime.

**Comment by bikallem** [comment]
Indeed that seems to be the case. Thanks.
