### ISSUE TITLE
Wayland dependencies

### ISSUE THREAD

**Issue by MagaTailor** [aochagavia/rocket#10]
Hi again,

Any chance of updating wayland dependencies to work around this [issue](https://github.com/rust-lang/rust/issues/29867)?

The version from `Cargo.toml` is affected whereas master seems to compile cleanly on ARM.

**Comment by aochagavia** [comment]
I don't have the time to work on this right now, but feel free to open a PR!

**Comment by MagaTailor** [comment]
Once I'm certain all other crates have been fixed I'll probably do that!
