### ISSUE TITLE
Crashes when build in release

### ISSUE THREAD

**Issue by ReinierMaas** [aochagavia/rocket#21]
Building the project in debug works:
'''
cargo run
'''

Then I tried building it in release mode and got a crash:
'''
cargo run --release
    Finished release [optimized] target(s) in 0.0 secs
     Running `target\release\rocket.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "CreateWindowEx function failed: Invalid access to memory location. (os error 998)"', ../src/libcore\result.rs:799
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: process didn't exit successfully: `target\release\rocket.exe` (exit code: 101)
'''

**Comment by johnthagen** [comment]
What platform and compiler are you using?  The following specs work for me on master in release mode:
- Windows 10 x64
- Rust Stable 0.12.0 (GNU)

**Comment by ReinierMaas** [comment]
Sorry for the late reaction I thought that responding to the email would post directly here.

I am compiling on:
- windows 10 x64
- rust nightly ...(latest version rustup update)... msvc

**Comment by johnthagen** [comment]
I think you'll need the [MinGW rust compiler](https://www.rust-lang.org/en-US/downloads.html#win-foot) for piston.

piston is only tested on Linux currently and thus, assumes GCC / MinGW compatible compiler for the C dependencies.  rustup should make it easy to try out the mingw compiler.

In case it helps, I have some walk through steps on my piston game: https://github.com/johnthagen/rust-belt#windows

**Comment by ReinierMaas** [comment]
I will try that, thank you for your help!

**Comment by aochagavia** [comment]
I was able to reproduce the issue. However, using the MinGW rust compiler didn't fix it.

**Comment by aochagavia** [comment]
I finally got it working by switching to the `nightly-i686-pc-windows-gnu` toolchain.

The toolchains that don't work are:
- `nightly-x86_64-pc-windows-gnu`
- `nightly-x86_64-pc-windows-msvc`

Could it be that Piston only works on x86?

**Comment by johnthagen** [comment]
I've been using stable GNU x64 on Windows since I started on Piston and haven't had any issues.  So maybe nightly-windows-x64 is broken?  Piston doesn't CI on Windows at all, so it's hard to know what is officially supported.

For example, this toolchain builds and runs `rocket` just fine:

```
rustup show
Default host: x86_64-pc-windows-gnu

stable-x86_64-pc-windows-gnu (default)
rustc 1.12.0 (3191fbae9 2016-09-23)
```

**Comment by ReinierMaas** [comment]
Okay I have taken the time to test it on my machine and it appears that it has something to do with the nightly versions of Rust.

It does work on msvc.

```
rustup default stable-x86_64-pc-windows-msvc
cargo run #works
cargo run --release #works

rustup default nightly-x86_64-pc-windows-msvc
cargo run #works
cargo run --release #doesn't work
```

Thank you for the information.
