### ISSUE TITLE
Switch to GraphicsTree piston2d backend when it is ready

### ISSUE THREAD

**Issue by aochagavia** [aochagavia/rocket#28]
Each time we draw an entity, Piston executes a draw call to the graphics card. This is incredibly expensive, but it can go unnoticed because the game does not have a big amount of entities. However, if we want others to learn from this project, it would be useful to use a backend that is able to scale. Fortunately, the [graphics_tree](https://github.com/PistonDevelopers/graphics_tree) backend seems to do exactly that, because it batches up the calls to draw and groups them together before sending them to the graphics card.

**Comment by johnthagen** [comment]
I did happen to notice some lag on a macbook pro when I let a bunch of enemies pile up and destroyed them all at once.

**Comment by aochagavia** [comment]
I just checked and the current version of graphics_tree is 0.3.0. Feel free to try it out and submit a PR in case it works.

**Comment by johnthagen** [comment]
@aochagavia What is your impression of the port from piston to ggez? Would you recommend ggez over piston for a game similar to rocket? I've been thinking about it for [rust-belt](https://github.com/johnthagen/rust-belt).

**Comment by aochagavia** [comment]
On a technical level, I see little difference. A mildly annoying consequence of using ggez is the dependency on SDL2, but it is not *that* bad.

On an ergonomics level, I like the documentation and the philosophy of making things simple. For instance, I expect adding sound to be a relatively painless thing to do.
