### ISSUE TITLE
OsError("glx::ChooseFBConfig failed")

### ISSUE THREAD

**Issue by Yamakaky** [aochagavia/rocket#4]
Hi
I have a problem while launching your game (wow, such stack trace !) :

```
     Running `target/release/rocket`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("glx::ChooseFBConfig failed")', /build/rust/src/rustc-1.1.0/src/libcore/result.rs:729
Process didn't exit successfully: `target/release/rocket` (exit code: 101)
```

glxinfo : http://0bin.net/paste/HKQrvHowf258NjzW#toozRH4d1ONFtB3NvxszDY5D6-CsdHkSgrMQktr1us3
graphic card : intel HD3000

**Comment by aochagavia** [comment]
I guess your system doesn't support one of the features I am using. Have you tried removing [this line](https://github.com/aochagavia/rocket/blob/866df0e76677a5a86f9f310cd46c77354ea1f3d9/src/main.rs#L30)? Maybe your graphics card doesn't support that.

**Comment by Yamakaky** [comment]
It works ! What does it do ?

**Comment by aochagavia** [comment]
It tells your graphic card to perform anti-aliasing of 8x, to make the edges of the figures smoother

**Comment by Yamakaky** [comment]
Ok. You should put it on the README, other people could be affected.

**Comment by MagaTailor** [comment]
Yup, just experienced the same thing on armv7 linux. Is there a way to downgrade OpenGL to something more compatible with SBC's like mine? (Odroid C1) to get acceleration via glshim?

Oops, just to test mesa I used 2_0 and it didn't work but 2_1 did.

**Comment by aochagavia** [comment]
@petevine Maybe the solution on https://github.com/aochagavia/rocket/issues/7#event-407847890 can help
