### ISSUE TITLE
Document UPS and BULLET_RATE

### ISSUE THREAD

**Issue by johnthagen** [aochagavia/rocket#43]
I think having a short doc comment for `game::{UPS, BULLET_RATE}` would help new readers better understand the update process.

**Comment by aochagavia** [comment]
Sounds great! Would you like to write it yourself? Or leave it to someone else?

**Comment by johnthagen** [comment]
I'd be happy to write it, though I don't know if I exactly understand `UPS` (I presume updates per second) but exactly how it interacts with the game / timer I wasn't sure about.

**Comment by aochagavia** [comment]
I took a look at the code and it seems to be updates per second indeed. I am surprised it doesn't match the number passed to `set_ups` (see [here](https://github.com/aochagavia/rocket/blob/cb9e30348f1fbee7fc6973ab5dc05664ec9d92cd/src/main.rs#L29)). The code was introduced by someone else in [this commit](https://github.com/aochagavia/rocket/commit/98597e3c61f5de98c65b9af869095d80755eefcd), but I cannot recall at this moment why it was necessary.

**Comment by johnthagen** [comment]
Nice catch, yeah something smells about it. `UPS` should at least match what's in `main.rs`.

`BULLET_RATE` seems fine. Looks like it keeps you from shooting hundreds of times per second.

**Comment by aochagavia** [comment]
I don't understand why we would need to multiply the rotation by the updates per second. I think it should be enough to multiply it by the delta-time.

**Comment by aochagavia** [comment]
Just removed `UPS` in https://github.com/aochagavia/rocket/commit/190b0f1a0257c4b31bdcb46bafdf200e3eb045e8

I also introduced more constants, which should help make things clearer (see the [diff](https://github.com/aochagavia/rocket/commit/190b0f1a0257c4b31bdcb46bafdf200e3eb045e8) here). Do you think the `BULLETS_PER_SECOND` is self-documenting now or do you still think we could use extra comments?

**Comment by johnthagen** [comment]
Looks great! Only small suggestion would be to document what the units of the `_SPEED` `const`s are. E.g. "Pixels per second"?

**Comment by aochagavia** [comment]
Check out https://github.com/aochagavia/rocket/commit/aaeb23a5412ff0c1445ffe286aed93c1a0615f94

Do you have any other suggestions?

**Comment by johnthagen** [comment]
Nope, looks great!
