### ISSUE TITLE
Panic if run from anywhere but project root.

### ISSUE THREAD

**Issue by Zarathustra30** [aochagavia/rocket#5]
On Windows, game::Game::new() panics if Rocket was called from anywhere but the project's root directory, because it looks for "resources/FiraMono-Bold.ttf" relative to the working directory Rocket was called from, not relative to Rocket nor the project root.

(I'm not sure if you're accepting issues or pull requests or anything. I just thought you ought to know.)

**Comment by aochagavia** [comment]
Well, you need that font to run the game. What would you expect instead of `panic!`ing?

**Comment by Zarathustra30** [comment]
The real issue is not the `panic!` but the looking in the wrong place. The simplest solution would be to use [`std::env::set_current_dir`](https://doc.rust-lang.org/std/env/fn.set_current_dir.html) to change the working directory to the project root. The only way I've found was to get [`std::env::current_exe`](https://doc.rust-lang.org/std/env/fn.current_exe.html) and go three directories up.

A slightly better solution is to copy the resources into the target with a build script, and then find them relative to `std::env::current_exe`. As a bonus, this makes pre-compiled binaries more portable.

Neither of those is the proverbial "best solution", but they are both "good enough".

**Comment by aochagavia** [comment]
I like your idea of copying the resources and using `current_exe`. Feel free to open a PR with this fix :wink:
