### ISSUE TITLE
Weird commit diff

### ISSUE THREAD

**Issue by aochagavia** [aochagavia/rocket#59]
I just committed (https://github.com/aochagavia/rocket/commit/2a52dfbb1ce74a979ebc4a986d158519e2436e21) and the diff is much bigger than I had expected. There seems to be something going on with line endings. Did they get converted from CRLF to LF? Or just the other way around? I cannot check this in a reliable way, since Git performs conversions automatically. @johnthagen could you help me with this?

**Comment by johnthagen** [comment]
`.gitattributes` was added in 6abd0b6403247899e9dd10a3c52bf5f47583a5c7.

What this should do is when the repo is cloned on Windows, use CRLF endings and Unix NL endings. What I'm guessing might have happened is that you had an older copy cloned from before this change and when you made updates, you still had NL on Windows or vice-versa.

One idea would be to revert the commit and do a clean clone which should normalize the line endings correctly, then try to reapply your commit.

**Comment by aochagavia** [comment]
Could it be that the repo itself has code with CRLF endings? And that when I commit they get transformed by git?

I just cloned the repository again, but `git status` prints the following (though I didn't touch any of the files!):

```
git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   LICENSE.md
        modified:   readme.md
        modified:   src/drawing/mod.rs
        modified:   src/drawing/point.rs
        modified:   src/drawing/size.rs
        modified:   src/models/bullet.rs
        modified:   src/models/enemy.rs
        modified:   src/models/mod.rs
        modified:   src/models/particle.rs
        modified:   src/models/player.rs
        modified:   src/models/vector.rs
        modified:   src/models/world.rs
        modified:   src/traits/mod.rs

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by johnthagen** [comment]
Yeah that is definitely a possibility. I might have had CRLF from before, and then I have been checking out on Windows so I never saw a difference. Seems like doing a clean checkout and committing it back should solve the problem?

I think this page talks about this issue and some ways to mitigate: https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings

**Comment by aochagavia** [comment]
Thanks! I think this should be solved now (see https://github.com/aochagavia/rocket/commit/d30d1b57df45f5dc94ba37fb70cca349102fd270)
