### ISSUE TITLE
Switch to piston core

### ISSUE THREAD

**Issue by aochagavia** [aochagavia/rocket#60]
See this comment: https://github.com/PistonDevelopers/piston_window/issues/186#issuecomment-282809553

**Comment by johnthagen** [comment]
@aochagavia We took a look at doing this for `rust-belt` and decided not to.

See https://github.com/johnthagen/rust-belt/issues/72 and https://github.com/johnthagen/rust-belt/pull/117 for details.

**Comment by aochagavia** [comment]
Thanks for your feedback... Then I think we could close this.
