### ISSUE TITLE
Broken game mechanic

### ISSUE THREAD

**Issue by alatiera** [aochagavia/rocket#68]
If you keep pressing space and either left or right arrow, it's almost impossible to lose :3

**Comment by aochagavia** [comment]
Do you have any suggestions as how to solve this?

**Comment by alatiera** [comment]
Not really, just found and played the wasm version like 5minutes ago so I am not really sure what's the process for generating the shots.

I might a look at the code later and see If I can come up with anything.

**Comment by aochagavia** [comment]
Note that, until now, I have ignored this problem since the project is meant as a self-contained example of how a game looks like in Rust, so people can learn from it. Therefore any improvements to the game logic should aim to keep the implementation as simple as it is now.

**Comment by mklcp** [comment]
Perhaps just disallow to have both the space key and the movement keys? Although the game is suddenly way more hard, with that.
