### ISSUE TITLE
Build error: thread '<main>' panicked

### ISSUE THREAD

**Issue by MightyPork** [aochagavia/rocket#7]
Well, I was curious, tried to build it.

Here's what I got:

```
   Compiling pistoncore-event v0.3.0
   Compiling piston v0.3.0
   Compiling piston2d-opengl_graphics v0.4.0
   Compiling pistoncore-glutin_window v0.4.0
     Running `target/release/rocket`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("glx::ChooseFBConfig failed")', src/libcore/result.rs:731
An unknown error occurred

To learn more, run the command again with --verbose.
```

No idea if it's in your code or somewhere in Rust, just thought you might like to have a look. I've just started learning Rust, so can't make much sense of anything here :P

**Comment by MightyPork** [comment]
oops, a dupe. But I now did what was suggested [here](https://github.com/aochagavia/rocket/issues/4), and...

```
$ cargo run --release
     Running `target/release/rocket`
[glutin] x error code=42 major=0 minor=0!
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("GL context creation failed")', src/libcore/result.rs:731
An unknown error occurred

To learn more, run the command again with --verbose.
```

**Comment by aochagavia** [comment]
Are you sure your graphics card supports OpenGL 3.2 and that it is installed in your computer? It seems to me that the problem lies there.

**Comment by MightyPork** [comment]
Not sure, maybe not. It's a ThinkPad x201 with Intel i5. Strange that a 2D game needs high-end graphics, but ok

**Comment by aochagavia** [comment]
I am not sure there is a need for high-end graphics. I guess it should work with older versions of OpenGL (you can try changing [this](https://github.com/aochagavia/rocket/blob/c4731961589e5251c4ba4cdb1db2d5e36d70febe/src/main.rs#L24) line). I didn't have any special reason to use 3.2.

Good luck learning Rust!

**Comment by MightyPork** [comment]
that did it, I tried `_2_1` and works without any problems. Nice game!

**Comment by aochagavia** [comment]
Feel free to submit a PR for this :wink:

**Comment by MagaTailor** [comment]
On my Odroid C1 it works using mesa after using the above method. To get acceleration via glshim it would have to go down to 1.5
