### ISSUE TITLE
Change repository tag line

### ISSUE THREAD

**Issue by acheronfail** [aochagavia/rocket#73]
`"A toy game in Rust, using Piston"` <-- should say ggez.

<img width="900" alt="screen shot 2017-12-19 at 6 46 46 pm" src="https://user-images.githubusercontent.com/34289614/34146177-0cc37568-e4ed-11e7-8c6d-239a289d4c16.png">

**Comment by aochagavia** [comment]
Done, thanks for pointing it out!
