### ISSUE TITLE
Destroying multiple enemies at the same time queues the sounds

### ISSUE THREAD

**Issue by aochagavia** [aochagavia/rocket#75]
Instead of playing the sounds at the same time, it queues them. Therefore, the sound is played multiple times after the enemies are destroyed.

**Comment by acheronfail** [comment]
We're currently waiting on an upstream fix for this: https://github.com/ggez/ggez/issues/208

**Comment by aochagavia** [comment]
@acheronfail just in case you were planning to submit more PRs this week, I wanted to let you know that I will have no internet access until the 31st (so don't be surprised when you don't get any feedback 😉 ). Couldn't find a better way to send you this message...

**Comment by aochagavia** [comment]
This has been fixed upstream in the meantime
