### ISSUE TITLE
Add powerups every n points/seconds

### ISSUE THREAD

**Issue by acheronfail** [aochagavia/rocket#77]
I've already got a prototype of this going, but I think the idea might work well:

* have a "powerup" spawn every n points/seconds (maybe every 500points/120sec?)
* powerups could be:
    * shooting powerups (shoot 3 bullets at once in different directions)
    * speed powerups (go faster, or make enemies slower)
    * shield powers (get an extra life for a limited amount of time)

Only question remains: How should they be rendered? I was thinking of a star-like structure that rotates in place and changes colour/size as time goes on.

**Comment by aochagavia** [comment]
I think going faster may make the game actually harder, so I would go for making enemies slower.

Shields are interesting as well... I think it would be nice to see that as some kind of force field around the player that effectively acts as an extra life.

Regarding how to render powerups, it seems sensible to render each of them differently depending on what they do. For instance, we could use the star-like structure you mention with an icon inside (a bullet, a shield or a snail [or something else that conveys a slow down of enemies]).

Btw, it seems worthwhile to add some mechanism to disallow the player from shooting uninterruptedly. What do you think of adding a progress bar that shows the heating of the guns? Whenever the bar is full, the player cannot shoot for 3 seconds or something like that.

**Comment by aochagavia** [comment]
A possible sound effect for when you pick up a powerup could be [this](https://vocaroo.com/i/s0Rl9TQTwxpT), which I happen to have created myself. This is my first attempt ever at creating a sound effect, so I am curious to know your opinion. In case it is complete garbage we can always resort to freesound 😉

**Comment by acheronfail** [comment]
Okay, so some powerups:

- Enemies slow down
- Player gains a (temporary?) force field
- Player shoots in different directions

I'll make some sprites for these powerups when I have some time 👍 

> Btw, it seems worthwhile to add some mechanism to disallow the player from shooting uninterruptedly. 

Definitely a good idea! Let's keep that as a separate PR though, I don't want this to be a huge change all at once.

> This is my first attempt ever at creating a sound effect, so I am curious to know your opinion.

I do like it! But when I originally looked for sounds for this game I was looking for more of an 8-bit feel if you know what I mean.. This is what I found on freesound before opening this issue: [powerup.ogg.zip](https://github.com/aochagavia/rocket/files/1609636/powerup.ogg.zip).

More than happy to include yours (this is your repo haha) - I'd like it if it were a little more retro 😆

**Comment by aochagavia** [comment]
Let's go with the sound you found on freesound. Eventually, we could land the powerups separately so you don't have to implement everything in one go.

I'll open an issue for the feature to limit the shooting time.

**Comment by acheronfail** [comment]
Closed by #79
