### ISSUE TITLE
Limit shooting

### ISSUE THREAD

**Issue by aochagavia** [aochagavia/rocket#78]
It seems worthwhile to add some mechanism to disallow the player from shooting uninterruptedly, as it ruins the game (the best strategy seems to indefinitely shoot in circles). For instance, we could add a progress bar that shows the heating of the guns. Whenever the bar is full, the player cannot shoot for 3 seconds or something like that.

**Comment by acheronfail** [comment]
We could also use the same mechanism to show how long the player's current powerup will continue to last.

**Comment by aochagavia** [comment]
Closed by #86
