### ISSUE TITLE
Find a better way to implement timers

### ISSUE THREAD

**Issue by aochagavia** [aochagavia/rocket#80]
Right now, when we want to trigger an event regularly, we manually check whether enough time has elapsed. I am not convinced by this approach, as it leads to some code repetition (we use the same pattern in many places). See below for an example:

```rust
if !state.world.player.is_dead
   && self.current_time - self.last_tail_particle > TRAIL_PARTICLE_RATE {
    self.last_tail_particle = self.current_time;
    state.world.particles.push(Particle::new(state.world.player.vector.clone().invert(), 0.5));
}
```

I am toying with a design to change this, so we don't need to reimplement the timer logic every time. The example below already works in one of my branches, though I wonder whether it is worth it. Maybe the introduced complexity outweights the DRY improvement.

```rust
// Init the timer in the constructor of the TimeController
tail_particle_timer: Timer::new(TRAIL_PARTICLE_RATE)

// ...

// Use it in the update function
if !state.world.player.is_dead {
    self.tail_particle_timer.update(self.current_time, || {
        state.world.particles.push(Particle::new(state.world.player.vector.clone().invert(),
                                                 0.5));
    });
}
```

@acheronfail what do you think?

**Comment by acheronfail** [comment]
I like the new approach - IMO it makes the logic simpler to reason about when updating the game state. 

Is there a possibility that we can bind the callbacks at init time, rather than passing newly instantiated functions each update?

**Comment by aochagavia** [comment]
Binding at init time is possible. You mean something like the code below?

```rust
// Construction
Timer::new(TRAIL_PARTICLE_RATE, |state| {
    state.world.particles.push(Particle::new(state.world.player.vector.clone().invert(), 0.5));
});

// Usage
self.tail_particle_timer.update(self.current_time, &mut state);
```

**Comment by aochagavia** [comment]
The only problem with that is that the update function is a bit less clear (i.e. you need to know where the timer is constructed in order to see what is happening)

**Comment by aochagavia** [comment]
Regarding performance, I expect the first approach I mentioned to have no overhead at all (that is, the compiled assembly should be the same as what we have right now). This closure would be statically dispatched, so basically we are just calling a function.

**Comment by aochagavia** [comment]
Now I think about it... Storing the closure in the timer at construction time (as you suggest) introduces indirection, because it requires boxing (there are ways to avoid this, but the code would become a huge mess). This in turn means that we end up with dynamic dispatch. I don't think the performance difference would be noticeable, but I guess you will find it interesting to know. I can explain it in more detail in case you are interested.

In the end, we could take either option, depending on what we think to be most readable. I have a slight preference for specifying the closure in the update function itself.

**Comment by acheronfail** [comment]
Oh okay - Rust is really my first time working with a compiled language, I'm usually more acquainted with scripting languages and such, so my understanding of static vs dynamic dispatch is really only what I could grasp from the Rust docs.

I originally thought of defining the functions at construction time only because I wasn't keen on re-creating functions each time the update is called - although thinking about the compiled assembly I see now that you're right that the performance difference would be negligible since the final product would be more or less the same.

Let's go with your original suggestion here and specify them in the update function itself 👍 

Though - if you wouldn't mind - explaining the differences in more detail would be a great help to my understanding of Rust 😆

**Comment by aochagavia** [comment]
I think the best is to illustrate with an example.

## Static dispatch

Imagine you have the following code:

```rust
fn main() {
    let result = f(42);
    println!("{}", result);
}

fn f(x: u32) -> u32 {
    x * x
}
```

In this example, the compiler knows *at compile time* (aka statically), that you are calling that function. That means it can perform lots of interesting optimizations. In this case, the number `42` will not even appear in the assembly. Instead, the optimizer will calculate the result right away and store `1764`. The resulting binary doesn't even need to do the calculation!

## Dynamic dispatch

Imagine you have the following code:

```rust
use std::env;

fn main() {
    let foo: Box<Fn(u32) -> u32> = if env::args().next().is_some() {
        Box::new(|x| x * x)
    } else {
        Box::new(|x| x * 2)
    };
    let result = foo(42);
    println!("{}", result);
}

fn f(x: u32) -> u32 {
    x * x
}
```

As you can see, the closure stored in `foo` will be different depending on the value of `env::args().next().is_some()`. That means that the compiler can no longer statically know which of the closures will be executed later on. It will need to use some kind of flag, unique to each closure, so it can *dynamically* (at runtime) identify it and call the right one. There are less optimizations you can do in that case.
