### ISSUE TITLE
Switch from f64 to f32 for geometry

### ISSUE THREAD

**Issue by aochagavia** [aochagavia/rocket#81]
Since `ggez` uses `f32` when drawing, it seems sensible to move our geometry to `f32` as well. We don't need `f64` precision.

As a consequence of this change, we could remove 25 `as f32` occurrences in `view.rs`, so itseems worthwhile.

**Comment by acheronfail** [comment]
I'll do this with pleasure! All those casts were really beginning to get on my nerves 😆

**Comment by acheronfail** [comment]
Funny that I've only noticed this just now, but is there any reason as to why we have an empty file (`src/geometry/position.rs` ) in the repo?

**Comment by aochagavia** [comment]
Nope, I just removed it and pushed the commit.

Btw, I don't know why `Vector` is in `models` instead of in `geometry`. I think it would be good to move it to `geometry`. Could you do that as well as a part of this? Otherwise I can open a different issue for it and do it later.

**Comment by acheronfail** [comment]
Yep no worries.

Also, since we use `dt` to affect the positions of the entities in the game, I think we should just change every `f64` to `f32` - I don't see it causing any issues, and it all the types are the same things should be simpler. What do you think?

**Comment by aochagavia** [comment]
Sounds good!
