### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by mikeWShef** [aochagavia/rocket#94]
Fresh install of rust, did not compile, it looks like a problem with a dependency (nalgebra-0.14.4)?

   Compiling specs v0.14.3
error[E0502]: cannot borrow `*self` as immutable because it is also borrowed as mutable
   --> C:\Users\44779\.cargo\registry\src\github.com-1ecc6299db9ec823\nalgebra-0.14.4\src\core\cg.rs:292:44
    |
292 |                 self[(j, i)] += shift[j] * self[(D::dim() - 1, i)];
    |                 ---------------------------^^^^-------------------
    |                 |                          |
    |                 |                          immutable borrow occurs here
    |                 mutable borrow occurs here
    |                 mutable borrow later used here

error: aborting due to previous error

For more information about this error, try `rustc --explain E0502`.
error: could not compile `nalgebra`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by weevilgenius** [comment]
Same issue here. This is mentioned in rustsim/nalgebra#561, and appears to be fixed in nalgebra 0.18 and newer.

**Comment by swedebugia** [comment]
The dependency tree looks like this. We have to update ggez to solve this it seems:
$ cargo tree
rocket v1.0.0 (/home/egil/src/rust/rocket)
├── geometry v0.1.0 (/home/egil/src/rust/rocket/geometry)
│   └── rand v0.6.5
│       ├── libc v0.2.69
│       ├── rand_chacha v0.1.1
│       │   └── rand_core v0.3.1
│       │       └── rand_core v0.4.2
│       │   [build-dependencies]
│       │   └── autocfg v0.1.7
│       ├── rand_core v0.4.2 (*)
│       ├── rand_hc v0.1.0
│       │   └── rand_core v0.3.1 (*)
│       ├── rand_isaac v0.1.1
│       │   └── rand_core v0.3.1 (*)
│       ├── rand_jitter v0.1.4
│       │   └── rand_core v0.4.2 (*)
│       ├── rand_os v0.1.3
│       │   ├── libc v0.2.69 (*)
│       │   └── rand_core v0.4.2 (*)
│       ├── rand_pcg v0.1.2
│       │   └── rand_core v0.4.2 (*)
│       │   [build-dependencies]
│       │   └── autocfg v0.1.7 (*)
│       └── rand_xorshift v0.1.1
│           └── rand_core v0.3.1 (*)
│       [build-dependencies]
│       └── autocfg v0.1.7 (*)
├── geometry-derive v0.1.0 (/home/egil/src/rust/rocket/geometry-derive)
│   ├── geometry v0.1.0 (/home/egil/src/rust/rocket/geometry) (*)
│   ├── quote v0.6.13
│   │   └── proc-macro2 v0.4.30
│   │       └── unicode-xid v0.1.0
│   └── syn v0.15.44
│       ├── proc-macro2 v0.4.30 (*)
│       ├── quote v0.6.13 (*)
│       └── unicode-xid v0.1.0 (*)
├── ggez v0.4.4
│   ├── app_dirs2 v2.0.4
│   │   └── xdg v2.2.0
│   ├── gfx v0.17.1
│   │   ├── derivative v1.0.4
│   │   │   ├── proc-macro2 v0.4.30 (*)
│   │   │   ├── quote v0.6.13 (*)
│   │   │   └── syn v0.15.44 (*)
│   │   ├── draw_state v0.8.0
│   │   │   └── bitflags v1.2.1
│   │   ├── gfx_core v0.8.3
│   │   │   ├── bitflags v1.2.1 (*)
│   │   │   ├── derivative v1.0.4 (*)
│   │   │   ├── draw_state v0.8.0 (*)
│   │   │   └── log v0.4.8
│   │   │       └── cfg-if v0.1.10
│   │   └── log v0.4.8 (*)
│   ├── gfx_device_gl v0.15.5
│   │   ├── gfx_core v0.8.3 (*)
│   │   ├── gfx_gl v0.5.0
│   │   │   [build-dependencies]
│   │   │   └── gl_generator v0.9.0
│   │   │       ├── khronos_api v2.2.0
│   │   │       ├── log v0.4.8 (*)
│   │   │       └── xml-rs v0.7.0
│   │   │           └── bitflags v1.2.1 (*)
│   │   └── log v0.4.8 (*)
│   ├── gfx_glyph v0.10.2
│   │   ├── backtrace v0.3.46
│   │   │   ├── backtrace-sys v0.1.35
│   │   │   │   └── libc v0.2.69 (*)
│   │   │   │   [build-dependencies]
│   │   │   │   └── cc v1.0.50
│   │   │   ├── cfg-if v0.1.10 (*)
│   │   │   ├── libc v0.2.69 (*)
│   │   │   └── rustc-demangle v0.1.16
│   │   ├── gfx v0.17.1 (*)
│   │   ├── gfx_core v0.8.3 (*)
│   │   ├── log v0.4.8 (*)
│   │   ├── ordered-float v0.5.2
│   │   │   ├── num-traits v0.1.43
│   │   │   │   └── num-traits v0.2.11
│   │   │   │       [build-dependencies]
│   │   │   │       └── autocfg v1.0.0
│   │   │   └── unreachable v1.0.0
│   │   │       └── void v1.0.2
│   │   ├── rusttype v0.5.2
│   │   │   ├── approx v0.1.1
│   │   │   ├── arrayvec v0.4.12
│   │   │   │   └── nodrop v0.1.14
│   │   │   ├── fnv v1.0.6
│   │   │   ├── linked-hash-map v0.5.2
│   │   │   ├── ordered-float v0.5.2 (*)
│   │   │   └── stb_truetype v0.2.8
│   │   │       └── stb_truetype v0.3.1
│   │   │           └── byteorder v1.3.4
│   │   ├── twox-hash v1.5.0
│   │   │   └── rand v0.7.3
│   │   │       ├── getrandom v0.1.14
│   │   │       │   ├── cfg-if v0.1.10 (*)
│   │   │       │   └── libc v0.2.69 (*)
│   │   │       ├── libc v0.2.69 (*)
│   │   │       ├── rand_chacha v0.2.2
│   │   │       │   ├── ppv-lite86 v0.2.6
│   │   │       │   └── rand_core v0.5.1
│   │   │       │       └── getrandom v0.1.14 (*)
│   │   │       └── rand_core v0.5.1 (*)
│   │   ├── unicode-normalization v0.1.12
│   │   │   └── smallvec v1.3.0
│   │   └── xi-unicode v0.1.0
│   ├── gfx_window_sdl v0.8.0
│   │   ├── gfx v0.17.1 (*)
│   │   ├── gfx_core v0.8.3 (*)
│   │   ├── gfx_device_gl v0.15.5 (*)
│   │   ├── log v0.4.8 (*)
│   │   └── sdl2 v0.31.0
│   │       ├── bitflags v0.7.0
│   │       ├── lazy_static v0.2.11
│   │       ├── libc v0.2.69 (*)
│   │       ├── num v0.1.42
│   │       │   ├── num-integer v0.1.42
│   │       │   │   └── num-traits v0.2.11 (*)
│   │       │   │   [build-dependencies]
│   │       │   │   └── autocfg v1.0.0 (*)
│   │       │   ├── num-iter v0.1.40
│   │       │   │   ├── num-integer v0.1.42 (*)
│   │       │   │   └── num-traits v0.2.11 (*)
│   │       │   │   [build-dependencies]
│   │       │   │   └── autocfg v1.0.0 (*)
│   │       │   └── num-traits v0.2.11 (*)
│   │       ├── rand v0.3.23
│   │       │   ├── libc v0.2.69 (*)
│   │       │   └── rand v0.4.6
│   │       │       └── libc v0.2.69 (*)
│   │       └── sdl2-sys v0.31.0
│   │           [build-dependencies]
│   │           └── cfg-if v0.1.10 (*)
│   ├── image v0.19.0
│   │   ├── byteorder v1.3.4 (*)
│   │   ├── gif v0.10.3
│   │   │   ├── color_quant v1.0.1
│   │   │   └── lzw v0.10.0
│   │   ├── jpeg-decoder v0.1.18
│   │   │   └── byteorder v1.3.4 (*)
│   │   ├── lzw v0.10.0 (*)
│   │   ├── num-derive v0.2.5
│   │   │   ├── proc-macro2 v0.4.30 (*)
│   │   │   ├── quote v0.6.13 (*)
│   │   │   └── syn v0.15.44 (*)
│   │   ├── num-iter v0.1.40 (*)
│   │   ├── num-rational v0.1.42
│   │   │   ├── num-integer v0.1.42 (*)
│   │   │   └── num-traits v0.2.11 (*)
│   │   ├── num-traits v0.2.11 (*)
│   │   └── png v0.12.0
│   │       ├── bitflags v1.2.1 (*)
│   │       ├── deflate v0.7.20
│   │       │   ├── adler32 v1.0.4
│   │       │   └── byteorder v1.3.4 (*)
│   │       ├── inflate v0.4.5
│   │       │   └── adler32 v1.0.4 (*)
│   │       └── num-iter v0.1.40 (*)
│   ├── log v0.4.8 (*)
│   ├── lyon v0.10.2
│   │   └── lyon_tessellation v0.10.2
│   │       ├── lyon_path v0.10.1
│   │       │   └── lyon_geom v0.10.1
│   │       │       ├── arrayvec v0.4.12 (*)
│   │       │       ├── euclid v0.17.3
│   │       │       │   └── num-traits v0.1.43 (*)
│   │       │       └── num-traits v0.1.43 (*)
│   │       └── sid v0.5.2
│   │           └── num-traits v0.1.43 (*)
│   ├── nalgebra v0.14.4
│   │   ├── alga v0.5.4
│   │   │   ├── approx v0.1.1 (*)
│   │   │   ├── num-complex v0.1.43
│   │   │   │   └── num-traits v0.2.11 (*)
│   │   │   └── num-traits v0.1.43 (*)
│   │   ├── approx v0.1.1 (*)
│   │   ├── generic-array v0.8.3
│   │   │   ├── nodrop v0.1.14 (*)
│   │   │   └── typenum v1.12.0
│   │   ├── matrixmultiply v0.1.15
│   │   │   └── rawpointer v0.1.0
│   │   ├── num-complex v0.1.43 (*)
│   │   ├── num-traits v0.1.43 (*)
│   │   ├── rand v0.4.6 (*)
│   │   └── typenum v1.12.0 (*)
│   ├── rodio v0.7.0
│   │   ├── cgmath v0.14.1
│   │   │   ├── approx v0.1.1 (*)
│   │   │   ├── num-traits v0.1.43 (*)
│   │   │   └── rand v0.3.23 (*)
│   │   ├── claxon v0.3.3
│   │   ├── cpal v0.8.2
│   │   │   ├── alsa-sys v0.1.2
│   │   │   │   └── libc v0.2.69 (*)
│   │   │   │   [build-dependencies]
│   │   │   │   └── pkg-config v0.3.17
│   │   │   ├── lazy_static v1.4.0
│   │   │   └── libc v0.2.69 (*)
│   │   ├── hound v3.4.0
│   │   ├── lazy_static v1.4.0 (*)
│   │   └── lewton v0.5.2
│   │       ├── byteorder v1.3.4 (*)
│   │       └── ogg v0.4.1
│   │           └── byteorder v1.3.4 (*)
│   ├── rusttype v0.5.2 (*)
│   ├── sdl2 v0.31.0 (*)
│   ├── serde v1.0.106
│   ├── serde_derive v1.0.106
│   │   ├── proc-macro2 v1.0.10
│   │   │   └── unicode-xid v0.2.0
│   │   ├── quote v1.0.3
│   │   │   └── proc-macro2 v1.0.10 (*)
│   │   └── syn v1.0.17
│   │       ├── proc-macro2 v1.0.10 (*)
│   │       ├── quote v1.0.3 (*)
│   │       └── unicode-xid v0.2.0 (*)
│   ├── smart-default v0.2.0
│   │   ├── quote v0.3.15
│   │   └── syn v0.11.11
│   │       ├── quote v0.3.15 (*)
│   │       ├── synom v0.11.3
│   │       │   └── unicode-xid v0.0.4
│   │       └── unicode-xid v0.0.4 (*)
│   ├── toml v0.4.10
│   │   └── serde v1.0.106 (*)
│   └── zip v0.3.3
│       ├── bzip2 v0.3.3
│       │   ├── bzip2-sys v0.1.8+1.0.8
│       │   │   └── libc v0.2.69 (*)
│       │   │   [build-dependencies]
│       │   │   └── cc v1.0.50 (*)
│       │   └── libc v0.2.69 (*)
│       ├── msdos_time v0.1.6
│       │   └── time v0.1.43
│       │       └── libc v0.2.69 (*)
│       ├── podio v0.1.6
│       └── time v0.1.43 (*)
├── itertools-num v0.1.3
│   └── num-traits v0.2.11 (*)
├── rand v0.6.5 (*)
├── specs v0.14.3
│   ├── crossbeam v0.4.1
│   │   ├── crossbeam-channel v0.2.6
│   │   │   ├── crossbeam-epoch v0.6.1
│   │   │   │   ├── arrayvec v0.4.12 (*)
│   │   │   │   ├── cfg-if v0.1.10 (*)
│   │   │   │   ├── crossbeam-utils v0.6.6
│   │   │   │   │   ├── cfg-if v0.1.10 (*)
│   │   │   │   │   └── lazy_static v1.4.0 (*)
│   │   │   │   ├── lazy_static v1.4.0 (*)
│   │   │   │   ├── memoffset v0.2.1
│   │   │   │   └── scopeguard v0.3.3
│   │   │   ├── crossbeam-utils v0.5.0
│   │   │   ├── parking_lot v0.6.4
│   │   │   │   ├── lock_api v0.1.5
│   │   │   │   │   ├── owning_ref v0.4.1
│   │   │   │   │   │   └── stable_deref_trait v1.1.1
│   │   │   │   │   └── scopeguard v0.3.3 (*)
│   │   │   │   └── parking_lot_core v0.3.1
│   │   │   │       ├── libc v0.2.69 (*)
│   │   │   │       ├── rand v0.5.6
│   │   │   │       │   ├── libc v0.2.69 (*)
│   │   │   │       │   └── rand_core v0.3.1 (*)
│   │   │   │       └── smallvec v0.6.13
│   │   │   │           └── maybe-uninit v2.0.0
│   │   │   │       [build-dependencies]
│   │   │   │       └── rustc_version v0.2.3
│   │   │   │           └── semver v0.9.0
│   │   │   │               └── semver-parser v0.7.0
│   │   │   ├── rand v0.5.6 (*)
│   │   │   └── smallvec v0.6.13 (*)
│   │   ├── crossbeam-deque v0.5.2
│   │   │   ├── crossbeam-epoch v0.5.2
│   │   │   │   ├── arrayvec v0.4.12 (*)
│   │   │   │   ├── cfg-if v0.1.10 (*)
│   │   │   │   ├── crossbeam-utils v0.5.0 (*)
│   │   │   │   ├── lazy_static v1.4.0 (*)
│   │   │   │   ├── memoffset v0.2.1 (*)
│   │   │   │   └── scopeguard v0.3.3 (*)
│   │   │   └── crossbeam-utils v0.5.0 (*)
│   │   ├── crossbeam-epoch v0.5.2 (*)
│   │   └── crossbeam-utils v0.5.0 (*)
│   ├── derivative v1.0.4 (*)
│   ├── fnv v1.0.6 (*)
│   ├── hibitset v0.5.4
│   │   ├── atom v0.3.5
│   │   └── rayon v1.3.0
│   │       ├── crossbeam-deque v0.7.3
│   │       │   ├── crossbeam-epoch v0.8.2
│   │       │   │   ├── cfg-if v0.1.10 (*)
│   │       │   │   ├── crossbeam-utils v0.7.2
│   │       │   │   │   ├── cfg-if v0.1.10 (*)
│   │       │   │   │   └── lazy_static v1.4.0 (*)
│   │       │   │   │   [build-dependencies]
│   │       │   │   │   └── autocfg v1.0.0 (*)
│   │       │   │   ├── lazy_static v1.4.0 (*)
│   │       │   │   ├── maybe-uninit v2.0.0 (*)
│   │       │   │   ├── memoffset v0.5.4
│   │       │   │   │   [build-dependencies]
│   │       │   │   │   └── autocfg v1.0.0 (*)
│   │       │   │   └── scopeguard v1.1.0
│   │       │   │   [build-dependencies]
│   │       │   │   └── autocfg v1.0.0 (*)
│   │       │   ├── crossbeam-utils v0.7.2 (*)
│   │       │   └── maybe-uninit v2.0.0 (*)
│   │       ├── either v1.5.3
│   │       └── rayon-core v1.7.0
│   │           ├── crossbeam-deque v0.7.3 (*)
│   │           ├── crossbeam-queue v0.2.1
│   │           │   ├── cfg-if v0.1.10 (*)
│   │           │   └── crossbeam-utils v0.7.2 (*)
│   │           ├── crossbeam-utils v0.7.2 (*)
│   │           ├── lazy_static v1.4.0 (*)
│   │           └── num_cpus v1.13.0
│   │               └── libc v0.2.69 (*)
│   ├── log v0.4.8 (*)
│   ├── mopa v0.2.2
│   ├── nonzero_signed v1.0.3
│   ├── rayon v1.3.0 (*)
│   ├── shred v0.7.2
│   │   ├── arrayvec v0.4.12 (*)
│   │   ├── fxhash v0.2.1
│   │   │   └── byteorder v1.3.4 (*)
│   │   ├── mopa v0.2.2 (*)
│   │   ├── rayon v1.3.0 (*)
│   │   └── smallvec v0.6.13 (*)
│   ├── shred-derive v0.5.1
│   │   ├── proc-macro2 v0.4.30 (*)
│   │   ├── quote v0.6.13 (*)
│   │   └── syn v0.15.44 (*)
│   ├── shrev v1.1.1
│   └── tuple_utils v0.2.0
└── structopt v0.2.18
    ├── clap v2.33.0
    │   ├── ansi_term v0.11.0
    │   ├── atty v0.2.14
    │   │   └── libc v0.2.69 (*)
    │   ├── bitflags v1.2.1 (*)
    │   ├── strsim v0.8.0
    │   ├── textwrap v0.11.0
    │   │   └── unicode-width v0.1.7
    │   ├── unicode-width v0.1.7 (*)
    │   └── vec_map v0.8.1
    └── structopt-derive v0.2.18
        ├── heck v0.3.1
        │   └── unicode-segmentation v1.6.0
        ├── proc-macro2 v0.4.30 (*)
        ├── quote v0.6.13 (*)
        └── syn v0.15.44 (*)
